version: "2"

linters:
  settings:
    staticcheck:
      checks:
        - all
        - '-ST1005'  # Ignore capitalized error strings
        - '-ST1003'  # Ignore ALL_CAPS
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
